services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Admin:23252002@"
    ports:
      - "1433:1433"
    volumes:
      - my-db:/var/opt/mssql
    
volumes:
  my-db: